name: Health Check

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://jp-pokedex.fly.dev/health
      - name: Notify on Health Check Success
        uses: rjstone/discord-webhook-notify@v4
        if: ${{ success() }}
        with:
          severity: info
          text: Health check succeeded!
          description: 'Health check succeeded!'
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Notify on Failure
        uses: rjstone/discord-webhook-notify@v4
        if: ${{ failure() }}
        with:
          severity: error
          text: Health check failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
